 image: node:14.16.0
 
 # Doing a full clone to be able to push back to Heroku.
 clone:
   depth: full
 
 pipelines:
   branches:
     # When code is pushed to the production branch it is deployed automatically to the production environment.
     production:
       - step:
           caches:
             - node
           script:
             - npm install
             - npm run start
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git production:master
 